import { mkdir, writeFile } from "node:fs/promises"
import { themes, themeTokenNames } from "../dist/themes.js"

const declaration = (definition) => [
  `  color-scheme: ${definition.colorScheme};`,
  "  font-family: Inter, Manrope, ui-sans-serif, system-ui, -apple-system, sans-serif;",
  "  font-synthesis: none;",
  ...themeTokenNames.map((name) => `  --${name}: ${definition.tokens[name]};`),
].join("\n")

const css = `/* Generated by @hyperserver/design-system. Do not edit dist/themes.css directly. */
:root,
:root[data-theme="peach-light"],
[data-hyper-theme="peach-light"] {
${declaration(themes["peach-light"])}
}

:root[data-theme="ember-dark"],
[data-hyper-theme="ember-dark"] {
${declaration(themes["ember-dark"])}
}
`

const dist = new URL("../dist/", import.meta.url)
await mkdir(dist, { recursive: true })
await writeFile(new URL("themes.css", dist), css)
